<?php
function xana_custom_post_types() {
    register_post_type('brocker', [
        'label'                 => __('Brocker', 'xana'),
        'labels'                => [
            'name'                  => __('کارگزاری', 'xana'),
            'singular_name'         => __('کارگزاری', 'xana'),
            'menu_name'             => __('کارگزاری ها', 'xana'),
            'name_admin_bar'        => __('کارگزاری', 'xana'),
            'archives'              => __('آرشیو کارگزاری ها', 'xana'),
            'attributes'            => __('Brocker Attributes', 'xana'),
            'parent_item_colon'     => __('Parent Brocker:', 'xana'),
            'all_items'             => __('همه کارگزاری ها', 'xana'),
            'add_new_item'          => __('افزودن کارگزاری', 'xana'),
            'add_new'               => __('افزودن', 'xana'),
            'new_item'              => __('کارگزاری جدید', 'xana'),
            'edit_item'             => __('ویرایش کارگزاری', 'xana'),
            'update_item'           => __('بروزرسانی کارگزاری', 'xana'),
            'view_item'             => __('مشاهده کارگزاری', 'xana'),
            'view_items'            => __('مشاهده کارگزاری ها', 'xana'),
            'search_items'          => __('جستجوی کارگزاری', 'xana'),
            'not_found'             => __('یافت نشد', 'xana'),
            'not_found_in_trash'    => __('Not found in Trash', 'xana'),
            'featured_image'        => __('تصویر شاخص', 'xana'),
            'set_featured_image'    => __('اختصاص تصویر شاخص', 'xana'),
            'remove_featured_image' => __('حذف تصویر شاخص', 'xana'),
            'use_featured_image'    => __('استفاده به عنوان تصویر شاخص', 'xana'),
            'insert_into_item'      => __('افزودن به کارگزاری', 'xana'),
            'uploaded_to_this_item' => __('Uploaded to this Brocker', 'xana'),
            'items_list'            => __('لیست کارگزاری ها', 'xana'),
            'items_list_navigation' => __('Brockers list navigation', 'xana'),
            'filter_items_list'     => __('فیلتر لیست کارگزاری ها', 'xana'),
        ],
        'description'           => __('Brocker Description', 'xana'),
        'public'                => true,
        'hierarchical'          => true,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'show_in_rest' => true,
        // 'rest_base' => "",
        // 'rest_namespace' => "",
        // 'rest_controller_class' => "",
        'menu_position'         => 5,
        // 'menu_icon' => "",
        'capability_type'       => 'page',
        // 'capabilities'       => [],
        // 'menu_icon'       => '',
        // 'map_meta_cap'       => '',
        'supports' => ['title', 'editor', 'comments', 'revisions', 'trackbacks', 'author', 'excerpt', 'page-attributes', 'thumbnail', 'custom-fields', 'post-formats'],
        // 'register_meta_box_cb' => cb,
        // 'taxonomies'            => array('group'),
        'can_export'            => true,
        'has_archive'           => true,
        // 'rewrite'           => [
        //     'slug' => 'Brockers'
        // ],

    ]);
    register_post_type('exchange', [
        'label'                 => __('صرافی', 'xana'),
        'labels'                => [
            'name'                  => __('صرافی', 'xana'),
            'singular_name'         => __('صرافی', 'xana'),
            'menu_name'             => __('صرافی ها', 'xana'),
            'name_admin_bar'        => __('صرافی', 'xana'),
            'archives'              => __('آرشیو صرافی ها', 'xana'),
            'attributes'            => __('Exchange Attributes', 'xana'),
            'parent_item_colon'     => __('Parent Exchange:', 'xana'),
            'all_items'             => __('همه صرافی ها', 'xana'),
            'add_new_item'          => __('افزودن صرافی جدید', 'xana'),
            'add_new'               => __('افزودن جدید', 'xana'),
            'new_item'              => __('صرافی جدید', 'xana'),
            'edit_item'             => __('ویرایش صرافی', 'xana'),
            'update_item'           => __('بروزرسانی صرافی', 'xana'),
            'view_item'             => __('مشاهده صرافی', 'xana'),
            'view_items'            => __('مشاهده صرافی ها', 'xana'),
            'search_items'          => __('جستجوی صرافی', 'xana'),
            'not_found'             => __('یافت نشد', 'xana'),
            'not_found_in_trash'    => __('Not found in Trash', 'xana'),
            'featured_image'        => __('تصویر شاخص', 'xana'),
            'set_featured_image'    => __('اختصاص تصویر شاخص', 'xana'),
            'remove_featured_image' => __('حذف تصویر شاخص', 'xana'),
            'use_featured_image'    => __('استفاده به انوان تصویر شاخص', 'xana'),
            'insert_into_item'      => __('افزودن به صرافی', 'xana'),
            'uploaded_to_this_item' => __('Uploaded to this Exchange', 'xana'),
            'items_list'            => __('لیست صرافی ها', 'xana'),
            'items_list_navigation' => __('Exchanges list navigation', 'xana'),
            'filter_items_list'     => __('فیلتر لیست صرافی ها', 'xana'),
        ],
        'description'           => __('Exchange Description', 'xana'),
        'public'                => true,
        'hierarchical'          => true,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'show_in_rest' => true,
        // 'rest_base' => "",
        // 'rest_namespace' => "",
        // 'rest_controller_class' => "",
        'menu_position'         => 6,
        // 'menu_icon' => "",
        'capability_type'       => 'page',
        // 'capabilities'       => [],
        // 'menu_icon'       => '',
        // 'map_meta_cap'       => '',
        'supports' => ['title', 'editor', 'comments', 'revisions', 'trackbacks', 'author', 'excerpt', 'page-attributes', 'thumbnail', 'custom-fields', 'post-formats'],
        // 'register_meta_box_cb' => cb,
        // 'taxonomies'            => array('group'),
        'can_export'            => true,
        'has_archive'           => true,
        // 'rewrite'           => [
        //     'slug' => 'Exchanges'
        // ],
    ]);
}
add_action('init', 'xana_custom_post_types', 0);
